spring:
  application:
    name: Travel

  datasource:
    url: jdbc:postgresql://192.168.0.101:5432/travel
    username:  myuser
    password:  mypassword
    driver-class-name: org.postgresql.Driver
